backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Blog Manager"
    files:
      - name: "blog"
        label: "Blog Posts"
        file: "blog.json"
        format: "json"
        fields:
          - name: "posts"
            label: "Posts"
            widget: "list"
            summary: "{{fields.title}} â€” {{fields.date}}"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "date", label: "Date", widget: "datetime", time_format: false, format: "YYYY-MM-DD" }
              - { name: "image", label: "Featured Image", widget: "image", required: false }
              - { name: "excerpt", label: "Excerpt", widget: "string", required: false }
              - { name: "body", label: "Full Post", widget: "text", required: false }
